# version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dataset:/var/lib/mysql-files
      - ./scripts:/docker-entrypoint-initdb.d
    command: --local_infile=1
    networks:
      - my-network
  
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    # env_file:
    #   - env
    networks:
      - my-network

  kafka:
    image: quay.io/debezium/kafka:3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      - env
    networks:
      - my-network

  debezium:
    image: quay.io/debezium/connect:3.0
    container_name: debezium
    depends_on:
      - kafka
      - mysql
    ports:
      - 8083:8083
    env_file:
      - env
    # volumes:
    #   - ./kafka-connect:/kafka/connect
    networks:
      - my-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - 8080:8080
    env_file:
      - env
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network: